### ISSUE TITLE
How to I change background color of currently selected PSI?

### ISSUE THREAD

**Issue by OptimisticLock** [JetBrains/psiviewer#11]
I vaguely recall that the currently selected PSI used to have black background and that I've changed it at some point. Now I have a hard time finding the way to change it again. When I click on a PSI element in the PsiViewer window, I know it moves somewhere, because my cursor disappears, but it does not highlight anything. It would be really nice to have the whole PSI element highlighted.

Thank you

**Comment by sylvanaar** [comment]
Duplicate `of #12
