### ISSUE TITLE
How to I change background color of currently selected PSI?

### ISSUE THREAD

**Issue by OptimisticLock** [JetBrains/psiviewer#12]
I vaguely recall that the currently selected PSI used to have black background and that I changed it. Now I am having a time finding a way to change the color back. When I click on a PSI element in the PsiViewer window, I know it moves somewhere, because my cursor disappears, but it does not highlight anything. It would be really nice to have the whole PSI element highlighted.

Thank you

**Comment by hurricup** [comment]
Seems duplicate with #11 

Have you tried this button? 
![button](http://joxi.net/brRDJ3BfQ90k72.jpg)

**Comment by OptimisticLock** [comment]
Woohoo! It works. :-) Thank you.

Only now it highlights black on black, impossible to see. How do I change the background? Or do I just switch to Darcula?

Sorry about the duplicate.

**Comment by hurricup** [comment]
I'm using default theme, and it highlights with purple.

**Comment by sylvanaar** [comment]
There is a options panel in the settings where you can change the color

Oh, it's broken, and no longer appears.

**Comment by sylvanaar** [comment]
Fixed in 2430c87a9a0506e7b145e851d06cbe60c9735f66
