### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by hurricup** [JetBrains/psiviewer#15]
```
[   9141]  ERROR - ellij.project.impl.ProjectImpl - idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent@35a0ee50 
java.lang.NullPointerException
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent.handleCurrentState(PsiViewerProjectComponent.java:184)
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent.access$100(PsiViewerProjectComponent.java:61)
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent$2.propertyChange(PsiViewerProjectComponent.java:127)
```

**Comment by sylvanaar** [comment]
Thanks, do you have a patch. Or reproductions steps. Will look when I have a chance.

**Comment by hurricup** [comment]
It looks like it's a problem of current eap

**Comment by hurricup** [comment]
please, check my pm in linkedin

**Comment by sylvanaar** [comment]
You'll have to talk to Collin about that - he owns the current repo.

**Comment by hurricup** [comment]
yes, but how to contact him ? couldn't find any contacts and seems he is not active here.

**Comment by cursive-ghost** [comment]
@hurricup Do you want to be added as a contributor?

**Comment by hurricup** [comment]
Yes I do. Also would be nice to be able to upload new releases to plugin repo.

**Comment by cursive-ghost** [comment]
Ok, I added you to this repo. I can't immediately figure out how to add you to the JetBrains plugin repo, though - if someone can investigate that and let me know I'll do that.

I very seldom use this plugin now, and haven't contributed for ages. If one of you would like to fork it, or would like to move it to an org like psiviewer/psiviewer or something, let me know.

**Comment by hurricup** [comment]
https://plugins.jetbrains.com/plugin/edit?pr=&pluginId=227
In developers section you may add another user. My nick is hurricup

**Comment by cursive-ghost** [comment]
Done!

**Comment by hurricup** [comment]
Thanks!

**Comment by hurricup** [comment]
Seems fixed in new eap build
