### ISSUE TITLE
Conflicting component name 'PsiViewerSettings'

### ISSUE THREAD

**Issue by hurricup** [JetBrains/psiviewer#17]
Conflicting with built-in psi viewer

```
[  50697]  ERROR - rationStore.ComponentStoreImpl - Conflicting component name 'PsiViewerSettings': class idea.plugin.psiviewer.controller.application.PsiViewerApplicationSettings and class com.intellij.internal.psiView.PsiViewerSettings 
```

**Comment by sylvanaar** [comment]
Yeah, they have their own PsiViewer that they use internally. We should change the component name to 
'plugins.psiviewer.PsiViewerSettings'

**Comment by sylvanaar** [comment]
You really have to go out of your way to make this happen - it wont affect our users

**Comment by hurricup** [comment]
built-in viewer shows formatting blocks. not possible to not using it

**Comment by sylvanaar** [comment]
Yes I know,. So it isn't a complicated fix. Why not fix it.

**Comment by hurricup** [comment]
Fixed in https://github.com/cmf/psiviewer/commit/2dc95e081c826eb162a799c35c4e834a022ee581
