### ISSUE TITLE
support modified PSI (via TemplateDataElementType.appendCurrentTemplateToken)

### ISSUE THREAD

**Issue by azrdev** [JetBrains/psiviewer#20]
This is similar to #18 

The language I'm implementing[1] is a grammar, whose constructs (with embedded "outer language" java/c++/… fragments) get translated into functions of the outer language, with contain those fragments. I'm successfully merging both with a MultiplePsiFilesPerDocumentFileViewProvider, but for the outer language to see a valid file (e.g. for java no functions outside a class), I have to inject text which isn't really there. This works so far using TemplateDataElementType.appendCurrentTemplateToken, however in the PsiViewer this invisibly moves the TextRanges of selected elements, i.e. an insertion of "sometext" will highlight the 8 characters after the place where it is (invisibly) inserted, and these offsets add up.

Also, the context menu actions "PSI dump to clipboard" only work for the base language, but I'd benefit from seeing the PSI like the template/outer language does.

[1] <https://github.com/azrdev/coco-idea-plugin/>

**Comment by hurricup** [comment]
What behavoiur do you expect in such case?

**Comment by azrdev** [comment]
1. any element selected in the PsiViewer should have the correct text range highlighted in the document, i.e. not shifted by previous "hidden" insertions
2. Dumping PSI (to clipboard) should work for template languages, too

**Comment by hurricup** [comment]
Could you please also provide an example that may be used with your plugin to illustrate the problem?

**Comment by azrdev** [comment]
@hurricup unfortunately I cannot reproduce the problem anymore, apparently (using IDEA 2017.3.4, PsiViewer 3.28.93 and my plugin on branch "next" / 649ab26 )

**Comment by hurricup** [comment]
Closing than?
