### ISSUE TITLE
Update tool window icon

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/psiviewer#3]
Usually see warn log message in .idea.log:
WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix jar:file:/home/vlad/.IntelliJIdea14/config/plugins/PsiViewer__1_.jar!/images/psiToolWindow.png

IDEA 13 and newer.
PsiViewer 3.28.73

**Comment by sylvanaar** [comment]
Will be in next build
