### ISSUE TITLE
Cannot install the latest snapshot on CLion

### ISSUE THREAD

**Issue by Machiry** [JetBrains/psiviewer#33]
Built using IntelliJIDE:

```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 23, 2019
```

Trying to install into:
```
CLion 2019.2.4
Build #CL-192.6817.32, built on October 9, 2019
```

**Comment by hurricup** [comment]
Are you building by yourself or are you trying to install from the plugin repo?

**Comment by Machiry** [comment]
Building it by myself

**Comment by Machiry** [comment]
Loaded into IntelliJ and then used `buildPlugin` gradle task

**Comment by hurricup** [comment]
Current sources configured to be built with 2019.1 and incompatible with 2019.2
Please, update https://github.com/cmf/psiviewer/blob/master/gradle.properties#L6 or just install plugin from the repository.

**Comment by Machiry** [comment]
I changed to:

```
name="PsiViewer"
platformVersion=192
platformBranch=.6817
platformBuild=.32
```
But getting the following error while trying to build:

```
   > Could not find com.jetbrains.intellij.idea:ideaIC:192.6817.32.
     Searched in the following locations:
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/192.6817.32/ideaIC-192.6817.32.pom
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/192.6817.32/ideaIC-192.6817.32.jar
     Required by:
```

Please, Is there any place that lists compatible version information?

**Comment by Machiry** [comment]
Nvm..it works..Thank You!!!
