### ISSUE TITLE
IDEA-230999 may be caused by PsiViewer

### ISSUE THREAD

**Issue by JThoennes** [JetBrains/psiviewer#35]
I have reported via YouTrack the IDEA issue
https://youtrack.jetbrains.com/issue/IDEA-230999
Do you think it may be caused by or related to the PsiViewer plugin?
After disabling PsiViewer it does not happen up to now.

**Comment by hurricup** [comment]
Looks like it doesn't. Anyway, easy to check - disable the plugin and try to reproduce.
