### ISSUE TITLE
Don't highlight code when PsiViewer window is closed

### ISSUE THREAD

**Issue by dima74** [JetBrains/psiviewer#36]
It would be nice that if user activates ["Highlight" option](https://i.stack.imgur.com/qyGAo.png) and closed PsiViewer tab, then highlighting would be disabled (until next time PsiViewer tab will be opened)

**Comment by hurricup** [comment]
Also, it shouldn't do anything while toolwindow  is closed. Currently it collects properties and affecting IDE performance.
