### ISSUE TITLE
Not able to build project in local 

### ISSUE THREAD

**Issue by sunz1e** [JetBrains/psiviewer#42]
Hello 
I am trying to explore the code but unable to build project in the local. Getting following error in console

A problem occurred configuring root project 'psiviewer'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not find com.jetbrains.intellij.idea:ideaIC:202.5428.22-EAP-SNAPSHOT.
     Searched in the following locations:
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/202.5428.22-EAP-SNAPSHOT/maven-metadata.xml
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/202.5428.22-EAP-SNAPSHOT/ideaIC-202.5428.22-EAP-SNAPSHOT.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by sunz1e** [comment]
Changing following properties in gradle worked. 

platformVersion=203
platformBranch=.4818-EAP-CANDIDATE-SNAPSHOT

**Comment by hurricup** [comment]
yes, this is correct solution.

**Comment by sunz1e** [comment]
Hello @hurricup,
I am trying to understand how the plugin works and I think we dont have any documentation.
I am thinking about debugging the plugin. I am mostly interested in:
1.  Getting the psi elements of the selected code block
2.  Highlighting the code when psi element is selected
like it is being done in PSI viewer. 
Could you point me to the entry point of the code flow?

**Comment by hurricup** [comment]
Can't say at once. I'm more like supporting it, not actively developing.

**Comment by sunz1e** [comment]
No Problem, Thanks for the reply. 
Hello @cmf, Could you help me with this? 

> I am trying to understand how the plugin works and I think we dont have any documentation.
> I am thinking about debugging the plugin. I am mostly interested in:
> 
> Getting the psi elements of the selected code block
> Highlighting the code when psi element is selected
> like it is being done in PSI viewer.
> Could you point me to the entry point of the code flow?

**Comment by cursive-ghost** [comment]
@meSunnySrivastava Sorry, I haven't worked on this plugin or used it for ages. It's probably time for someone to fork it and develop it from there.
