### ISSUE TITLE
PsiViewer causes "close unmodified" to stop working.

### ISSUE THREAD

**Issue by annitya** [JetBrains/psiviewer#6]
For some reason this does not apply to regular-project files.

**Comment by sylvanaar** [comment]
Can you elaborate?

**Comment by annitya** [comment]
I've had a hard time narrowing it down. I first submitted the issue directly to Jetbrains, they then suggested I disable all third-party plugins. So I did; enabling them one at a time.

Files which are not part of the project are somehow marked as modified while this plugin is active. They do not show up in changelists or anything like that, but when I try to clean up my editor by closing all unmodified files, they will remain open.

After disabling PsiViewer, I have seen the issue resurface from time to time, but not to the same extent as before.

If your first thought isn't: "I know what's causing this" after reading my somewhat vague description, I suggest you wait.

Hopefully the patterns will be made clear to me in the not too distant future.

**Comment by sylvanaar** [comment]
As far as I know PsiViewer doesn't modify the document, we can keep an eye out though for any issue if you can get the reproduction steps down.

**Comment by annitya** [comment]
Seems to be related to a different plugin. I shall contact them instead. Sorry for the inconvenience!

**Comment by sylvanaar** [comment]
Thanks
