### ISSUE TITLE
How does this plugin work ?

### ISSUE THREAD

**Issue by helmus** [JetBrains/psiviewer#7]
If I go to Psi viewer settings, I get a whole bunch of color settings, how do I actually use this ?

**Comment by sylvanaar** [comment]
It is for understanding how a document's PSI structure is laid out. You should look for the tool window and then explore the current source file by clicking on various parts of the source or by clicking on various nodes in the PSI tree.

![image](https://cloud.githubusercontent.com/assets/114616/9146686/a5095f2e-3d13-11e5-9050-a723decd2665.png)

**Comment by sylvanaar** [comment]
Was that enough to answer your question?

**Comment by helmus** [comment]
@sylvanaar  Yes thank you ! I found the tab. ?
I got confused because there are some Psi short cut bindings that apparently do nothing.
